### ISSUE TITLE
Looks amazing, cant wait to see where it goes!

### ISSUE THREAD

**Issue by AsternA** [pinikeizman/home-scheduler#1]
Looks good Pini!

I also have a few ideas for a RPi project but i am waiting until we move into our new house to start them. Maybe by then i can use this project as a template!

**Comment by pinikeizman** [comment]
Thanks @AsternA ❤️ 
Sure, feel free to use this repo as your template. Maybe I'll do it myself, create another skeleton project to fork as base for future projects.
